'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronRight, CircleAlert, Clock3, FileCheck2, Heart, Home, MapPin, Search, ShieldCheck, Sparkles, UserRound, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';

type Listing = { id:number; agency:'SH'|'LH'; program:string; title:string; area:string; homeType:string; units:string; deposit:string; rent:string; deadline:string; days:number; match:number; reasons:string[]; color:string };
const listings: Listing[] = [
 {id:1,agency:'SH',program:'청년안심주택',title:'마곡 센트럴타워',area:'서울 강서구 마곡동',homeType:'오피스텔 · 전용 25㎡',units:'공급 28세대',deposit:'4,200만원',rent:'월 31만원',deadline:'09.12',days:5,match:94,reasons:['서울 거주','청년','소득 80% 이하'],color:'#0a7664'},
 {id:2,agency:'LH',program:'행복주택',title:'고양창릉 A-4BL',area:'경기 고양시 덕양구',homeType:'아파트 · 전용 36㎡',units:'공급 120세대',deposit:'3,580만원',rent:'월 18만원',deadline:'09.16',days:9,match:89,reasons:['무주택','1인 가구','자산 기준 충족'],color:'#3764c8'},
 {id:3,agency:'SH',program:'매입임대',title:'성수 리버하우스',area:'서울 성동구 성수동',homeType:'다세대 · 전용 29㎡',units:'공급 16세대',deposit:'2,900만원',rent:'월 27만원',deadline:'09.21',days:14,match:83,reasons:['무주택','서울 생활권','소득 기준 충족'],color:'#d1653f'},
];
const documents = [
 {label:'주민등록등본',source:'정부24'}, {label:'가족관계증명서',source:'전자가족관계등록시스템'}, {label:'소득금액증명원',source:'홈택스'}, {label:'금융정보 제공동의서',source:'공고문 서식'},
];

export default function HomePage(){
 const [agency,setAgency]=useState('all'); const [region,setRegion]=useState('서울 전체'); const [query,setQuery]=useState(''); const [saved,setSaved]=useState<number[]>([2]); const [checkedDocs,setCheckedDocs]=useState<number[]>([0,3]);
 const filtered=useMemo(()=>listings.filter(item=>(agency==='all'||item.agency.toLowerCase()===agency)&&(region==='서울 전체'||item.area.includes(region.replace('서울 ','')))&&`${item.title} ${item.area} ${item.program}`.toLowerCase().includes(query.toLowerCase())),[agency,region,query]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool={name:'set_housing_filters',title:'공공주택 필터 설정',description:'화면의 LH·SH 기관, 지역, 검색어 필터를 한 번에 설정합니다.',inputSchema:{type:'object',properties:{agency:{type:'string',enum:['all','sh','lh']},region:{type:'string',enum:['서울 전체','서울 강서구','서울 성동구']},query:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('필터 입력은 객체여야 합니다.');const next=input as {agency?:string;region?:string;query?:string};if(next.agency&&!['all','sh','lh'].includes(next.agency))throw new Error('지원하지 않는 기관입니다.');if(next.region&&!['서울 전체','서울 강서구','서울 성동구'].includes(next.region))throw new Error('지원하지 않는 지역입니다.');if(next.agency)setAgency(next.agency);if(next.region)setRegion(next.region);if(typeof next.query==='string')setQuery(next.query);return{agency:next.agency??agency,region:next.region??region,query:next.query??query,status:'updated'};}};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);}catch{}
  return()=>lifecycle.abort();
 },[agency,region,query]);
 return <main className="min-h-screen bg-background text-foreground">
  <header className="sticky top-0 z-20 border-b bg-background/92 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 lg:px-8">
   <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Home className="size-[19px]" strokeWidth={2.5}/></div><div><p className="font-brand text-[19px] font-extrabold tracking-[-0.04em]">내집레이더</p><p className="-mt-0.5 text-[11px] font-semibold text-muted-foreground">공공주택 맞춤 탐색</p></div></div>
   <nav className="hidden items-center gap-8 text-sm font-semibold md:flex" aria-label="주요 메뉴"><a className="text-primary" href="#listings">맞춤 공고</a><a className="text-muted-foreground hover:text-foreground" href="#documents">서류함</a><a className="text-muted-foreground hover:text-foreground" href="#profile">내 조건</a></nav>
   <Button variant="outline" className="rounded-xl"><UserRound className="size-4"/> 내 조건 수정</Button>
  </div></header>
  <section className="mx-auto max-w-[1440px] px-5 py-7 lg:px-8 lg:py-10">
   <div className="mb-8 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.75fr)]">
    <div className="hero-panel relative overflow-hidden rounded-[28px] p-7 text-white md:p-9"><div className="relative z-10 max-w-2xl">
     <span className="mb-4 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold backdrop-blur-sm"><Sparkles className="size-3.5"/> 조건 분석 완료</span>
     <h1 className="font-brand text-[32px] font-extrabold leading-[1.22] tracking-[-0.045em] md:text-[42px]">지금 지원 가능한 공공주택이<br className="hidden sm:block"/> <span className="text-[#9be5cb]">총 12곳</span> 있어요</h1>
     <p className="mt-3 text-[15px] leading-6 text-white/72">서울 거주 · 만 29세 · 1인 가구 · 무주택 조건을 기준으로 분석했어요.</p><div className="mt-6 flex flex-wrap gap-2">{['청년','무주택','1인 가구','월소득 243만원'].map(tag=><span key={tag} className="rounded-lg bg-white/10 px-3 py-2 text-xs font-bold">{tag}</span>)}</div>
    </div><div className="hero-orbit" aria-hidden="true"><MapPin className="size-8"/></div></div>
    <aside id="profile" className="rounded-[28px] border bg-card p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-bold">자격 프로필</p><p className="mt-1 text-xs text-muted-foreground">마지막 갱신: 오늘</p></div><span className="grid size-10 place-items-center rounded-full bg-secondary text-primary"><ShieldCheck className="size-5"/></span></div>
     <div className="space-y-4"><div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">프로필 완성도</span><strong className="text-primary">86%</strong></div><Progress value={86} className="h-2"/></div><div className="grid grid-cols-2 gap-2 text-sm"><ProfileDatum icon={<UserRound/>} label="나이" value="만 29세"/><ProfileDatum icon={<WalletCards/>} label="월소득" value="243만원"/><ProfileDatum icon={<Home/>} label="주택" value="무주택"/><ProfileDatum icon={<MapPin/>} label="거주지" value="서울"/></div><button className="flex w-full items-center justify-between rounded-xl bg-secondary px-4 py-3 text-left text-sm font-bold text-primary">자산 정보를 입력하면 더 정확해져요 <ChevronRight className="size-4"/></button></div>
    </aside>
   </div>
   <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
    <section id="listings" className="min-w-0"><div className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">MATCHED HOUSING</p><h2 className="font-brand text-2xl font-extrabold tracking-[-0.04em]">내 조건에 맞는 공고</h2></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-10 rounded-xl pl-9 sm:w-56" placeholder="지역·단지 검색" aria-label="지역 또는 단지 검색"/></div><Select value={region} onValueChange={value=>setRegion(value??'서울 전체')}><SelectTrigger className="h-10 min-w-32 rounded-xl" aria-label="지역 선택"><SelectValue/></SelectTrigger><SelectContent>{['서울 전체','서울 강서구','서울 성동구'].map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div></div>
     <div className="mb-4 flex items-center justify-between border-b"><Tabs value={agency} onValueChange={setAgency}><TabsList className="h-11 bg-transparent p-0">{[['all','전체 12'],['sh','SH 7'],['lh','LH 5']].map(([value,label])=><TabsTrigger key={value} className="rounded-none border-b-2 border-transparent px-4 data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:shadow-none" value={value}>{label}</TabsTrigger>)}</TabsList></Tabs><span className="hidden text-xs text-muted-foreground sm:block">적합도 높은 순</span></div>
     <div className="space-y-3">{filtered.map(item=><article key={item.id} className="listing-card group rounded-2xl border bg-card p-5 transition-all hover:-translate-y-0.5 hover:shadow-lg"><div className="grid gap-5 md:grid-cols-[auto_1fr_auto] md:items-center">
      <div className="flex size-14 items-center justify-center rounded-2xl text-sm font-black text-white" style={{background:item.color}}>{item.agency}</div><div className="min-w-0"><div className="mb-1.5 flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-muted-foreground">{item.program}</span><span className="rounded-md bg-[#fff1ed] px-2 py-0.5 text-[11px] font-extrabold text-[#c34e2d]">D-{item.days}</span></div><h3 className="truncate font-brand text-xl font-extrabold tracking-[-0.035em]">{item.title}</h3><p className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground"><span className="inline-flex items-center gap-1"><MapPin className="size-3.5"/>{item.area}</span><span>{item.homeType}</span><span>{item.units}</span></p><div className="mt-3 flex flex-wrap gap-1.5">{item.reasons.map(reason=><span key={reason} className="rounded-md bg-secondary px-2 py-1 text-[11px] font-bold text-secondary-foreground"><Check className="mr-1 inline size-3 text-primary"/>{reason}</span>)}</div></div>
      <div className="flex items-center justify-between gap-5 border-t pt-4 md:block md:min-w-36 md:border-l md:border-t-0 md:pl-5 md:pt-0"><div><p className="text-[11px] font-bold text-muted-foreground">예상 주거비</p><p className="mt-0.5 text-sm font-extrabold">보증금 {item.deposit}</p><p className="text-sm font-extrabold">{item.rent}</p></div><div className="mt-3 flex items-center gap-2"><span className="mr-auto text-xs font-black text-primary">적합 {item.match}%</span><button onClick={()=>setSaved(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])} aria-label={`${item.title} 관심 공고 저장`} className={`grid size-9 place-items-center rounded-lg border ${saved.includes(item.id)?'border-primary bg-primary text-white':'hover:bg-secondary'}`}><Heart className="size-4" fill={saved.includes(item.id)?'currentColor':'none'}/></button><button aria-label={`${item.title} 상세 보기`} className="grid size-9 place-items-center rounded-lg bg-foreground text-background"><ArrowRight className="size-4"/></button></div></div>
     </div></article>)}{filtered.length===0&&<div className="rounded-2xl border border-dashed p-12 text-center text-sm text-muted-foreground">선택한 조건에 맞는 샘플 공고가 없습니다.</div>}</div>
     <div className="mt-4 flex items-start gap-2 rounded-xl bg-secondary/70 px-4 py-3 text-xs leading-5 text-muted-foreground"><CircleAlert className="mt-0.5 size-4 shrink-0"/><p>현재 화면의 공고와 금액은 기능 확인용 샘플입니다. 실제 지원 전 반드시 LH·SH 공식 공고문에서 모집 기간과 자격을 확인하세요.</p></div>
    </section>
    <aside id="documents" className="space-y-4 xl:sticky xl:top-24"><section className="rounded-[24px] border bg-card p-5 shadow-sm"><div className="mb-5 flex items-start justify-between"><div><p className="section-kicker">DOCUMENTS</p><h2 className="font-brand text-xl font-extrabold tracking-[-0.035em]">공통 준비 서류</h2></div><span className="grid size-10 place-items-center rounded-xl bg-[#e8f5f0] text-primary"><FileCheck2 className="size-5"/></span></div><div className="mb-4"><div className="mb-2 flex justify-between text-xs"><span className="font-bold">{checkedDocs.length} / 4 준비됨</span><span className="text-muted-foreground">{checkedDocs.length*25}%</span></div><Progress value={checkedDocs.length*25} className="h-1.5"/></div><div className="space-y-1">{documents.map((doc,index)=><label key={doc.label} className="flex cursor-pointer items-start gap-3 rounded-xl p-3 hover:bg-secondary"><Checkbox checked={checkedDocs.includes(index)} onCheckedChange={()=>setCheckedDocs(current=>current.includes(index)?current.filter(id=>id!==index):[...current,index])} className="mt-0.5"/><span className="min-w-0"><span className={`block text-sm font-bold ${checkedDocs.includes(index)?'text-muted-foreground line-through':''}`}>{doc.label}</span><span className="block truncate text-[11px] text-muted-foreground">발급: {doc.source}</span></span></label>)}</div><Button className="mt-4 h-11 w-full rounded-xl">서류 체크리스트 보기 <ChevronRight className="size-4"/></Button></section>
     <section className="rounded-[24px] bg-[#182b2a] p-5 text-white"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/10 text-[#9be5cb]"><CalendarDays className="size-5"/></span><div><p className="text-xs text-white/55">가장 가까운 마감</p><p className="font-bold">마곡 센트럴타워</p></div></div><div className="my-4 h-px bg-white/10"/><div className="flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-sm text-white/72"><Clock3 className="size-4"/> 9월 12일 17:00</span><strong className="text-[#9be5cb]">D-5</strong></div></section>
    </aside>
   </div>
  </section>
 </main>
}
function ProfileDatum({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border bg-background p-3"><div className="mb-2 flex size-7 items-center justify-center rounded-lg bg-secondary text-primary [&>svg]:size-3.5">{icon}</div><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-0.5 font-bold">{value}</p></div>}
